### ISSUE TITLE
Selecting item in inventory menu while hands are full leads to errors on client.

### ISSUE THREAD

**Issue by factorsofx** [hansonry/nodestation#1]
To recreate: Unequip any two items, then open the inventory menu and attempt to select a third. It becomes impossible to move or exit the menu.

**Comment by hansonry** [comment]
I see it I know what I did wrong. Thanks.

**Comment by hansonry** [comment]
Fixed by commit 00ecd6ee3f6b79080e34061f4ddf0e3f0e0f0d68
